import { AudioItem, TasbihState } from './types';

// Helper to pad numbers
const padThree = (num: number) => String(num).padStart(3, '0');
const padTwo = (num: number) => String(num).padStart(2, '0');

// Compact metadata for the 114 Surahs of the Holy Quran
const SURAH_METADATA = [
  { en: "Al-Fatihah", ar: "الفاتحة", translation: "The Opening", urdu: "شروع کرنے والی", verses: 7, type: "Meccan", benefits: "Healing, guidance, and cures physical and spiritual illnesses.", duration: "0:45" },
  { en: "Al-Baqarah", ar: "البقرة", translation: "The Cow", urdu: "گائے", verses: 286, type: "Medinan", benefits: "Protects home from Shaytan (devils), evil eye, and magic.", duration: "120:00" },
  { en: "Ali 'Imran", ar: "آل عمران", translation: "Family of Imran", urdu: "عمران کی آل", verses: 200, type: "Medinan", benefits: "Brings peace, prosperity, and protection from debt.", duration: "85:00" },
  { en: "An-Nisa", ar: "النساء", translation: "The Women", urdu: "عورتیں", verses: 176, type: "Medinan", benefits: "Fulfills rights of family members and grants forgiveness.", duration: "90:00" },
  { en: "Al-Ma'idah", ar: "المائدة", translation: "The Table Spread", urdu: "دسترخوان", verses: 120, type: "Medinan", benefits: "Reduces hunger, brings spiritual tranquility and safety.", duration: "72:00" },
  { en: "Al-An'am", ar: "الأنعام", translation: "The Cattle", urdu: "مویشی", verses: 165, type: "Meccan", benefits: "Praise of Allah, absolute protection from enemy plots.", duration: "78:00" },
  { en: "Al-A'raf", ar: "الأعراف", translation: "The Heights", urdu: "اونچی جگہیں", verses: 206, type: "Meccan", benefits: "Safeguard against adversaries and spiritual blindness.", duration: "88:00" },
  { en: "Al-Anfal", ar: "الأنفال", translation: "The Spoils of War", urdu: "مالِ غنیمت", verses: 75, type: "Medinan", benefits: "Grants release from imprisonment and protection from tyranny.", duration: "38:00" },
  { en: "At-Tawbah", ar: "التوبة", translation: "The Repentance", urdu: "توبہ", verses: 129, type: "Medinan", benefits: "Repentance accepted, forgiveness, barrier against hypocrisy.", duration: "70:00" },
  { en: "Yunus", ar: "يونس", translation: "Jonah", urdu: "یونس علیہ السلام", verses: 109, type: "Meccan", benefits: "Recognizing absolute guidance, overcomes heavy obstacles.", duration: "53:05" },
  { en: "Hud", ar: "هود", translation: "Hud", urdu: "ہود علیہ السلام", verses: 123, type: "Meccan", benefits: "Courage, physical strength, and relief from extreme worries.", duration: "59:00" },
  { en: "Yusuf", ar: "يوسف", translation: "Joseph", urdu: "یوسف علیہ السلام", verses: 111, type: "Meccan", benefits: "Elimination of jealousy from people, grants honor and beauty.", duration: "58:00" },
  { en: "Ar-Ra'd", ar: "الرعد", translation: "The Thunder", urdu: "گرج", verses: 43, type: "Medinan", benefits: "Eases calculation on Day of Judgment, protection from quick death.", duration: "25:00" },
  { en: "Ibrahim", ar: "ابراهيم", translation: "Abraham", urdu: "ابراہیم علیہ السلام", verses: 52, type: "Meccan", benefits: "Relief from poverty, protection from fits of anger.", duration: "24:00" },
  { en: "Al-Hijr", ar: "الحجر", translation: "The Rocky Tract", urdu: "پتھریلی مٹی", verses: 99, type: "Meccan", benefits: "Brings success, blessings in trade and financial prosperity.", duration: "19:00" },
  { en: "An-Nahl", ar: "النحل", translation: "The Bee", urdu: "شہد کی مکھی", verses: 128, type: "Meccan", benefits: "Protection against seventy kinds of mental and physical troubles.", duration: "48:00" },
  { en: "Al-Isra", ar: "الإسراء", translation: "The Night Journey", urdu: "معراج", verses: 111, type: "Meccan", benefits: "Wisdom, helps child express speech and physical growth.", duration: "45:00" },
  { en: "Al-Kahf", ar: "الكهف", translation: "The Cave", urdu: "غار", verses: 110, type: "Meccan", benefits: "Illuminates light till next Friday, protects from Dajjal trials.", duration: "46:00" },
  { en: "Maryam", ar: "مريم", translation: "Mary", urdu: "مریم علیہ السلام", verses: 98, type: "Meccan", benefits: "Prosperity, childbearing blessings, and peace of mind.", duration: "32:00" },
  { en: "Taha", ar: "طه", translation: "Ta-Ha", urdu: "طٰہٰ", verses: 135, type: "Meccan", benefits: "Ease of marriage relationships, pardoning of past sins.", duration: "39:00" },
  { en: "Al-Anbya", ar: "الأنبياء", translation: "The Prophets", urdu: "انبیاء", verses: 112, type: "Meccan", benefits: "Relief from distress, inner anxiety, and heavy obstacles.", duration: "37:00" },
  { en: "Al-Hajj", ar: "الحج", translation: "The Pilgrimage", urdu: "حج", verses: 78, type: "Meccan", benefits: "Assistance to perform Hajj, increases crops and business.", duration: "38:00" },
  { en: "Al-Mu'minun", ar: "المؤمنون", translation: "The Believers", urdu: "مومنین", verses: 118, type: "Meccan", benefits: "Grants final status of true believer and safety at death.", duration: "28:00" },
  { en: "An-Nur", ar: "النور", translation: "The Light", urdu: "روشنی", verses: 64, type: "Medinan", benefits: "Protects family sanctity, prevents bad habits and bad thoughts.", duration: "33:00" },
  { en: "Al-Furqan", ar: "الفرقان", translation: "The Criterion", urdu: "کسوٹی", verses: 77, type: "Meccan", benefits: "Bypasses reckoning on Judgement day if recited with belief.", duration: "24:00" },
  { en: "Ash-Shu'ara", ar: "الشعراء", translation: "The Poets", urdu: "شاعر", verses: 227, type: "Meccan", benefits: "Protects home from theft and drowning hazards.", duration: "34:00" },
  { en: "An-Naml", ar: "النمل", translation: "The Ant", urdu: "چیونٹی", verses: 93, type: "Meccan", benefits: "Secures safety from dangerous pests or wild beasts.", duration: "25:00" },
  { en: "Al-Qasas", ar: "القصص", translation: "The Stories", urdu: "کہانیاں", verses: 88, type: "Meccan", benefits: "Heals major physical ailments and reduces acute fears.", duration: "33:00" },
  { en: "Al-'Ankabut", ar: "العنكبوت", translation: "The Spider", urdu: "مکڑی", verses: 69, type: "Meccan", benefits: "Peace, tranquil sleeping pattern, and stable mental health.", duration: "23:00" },
  { en: "Ar-Rum", ar: "الروم", translation: "The Romans", urdu: "رومی", verses: 60, type: "Meccan", benefits: "Forgiveness of sins equal to the number of angels.", duration: "19:00" },
  { en: "Luqman", ar: "لقمان", translation: "Luqman", urdu: "لقمان علیہ السلام", verses: 34, type: "Meccan", benefits: "Protects from Satan's whispers, cures stomach pains.", duration: "14:00" },
  { en: "As-Sajdah", ar: "السجدة", translation: "The Prostration", urdu: "سجدہ", verses: 30, type: "Meccan", benefits: "A companion in the grave; light on the Day of Judgment.", duration: "10:00" },
  { en: "Al-Ahzab", ar: "الأحزاب", translation: "The Combined Forces", urdu: "شہر", verses: 73, type: "Medinan", benefits: "Safety in grave, closeness to Prophet Muhammad (PBUH).", duration: "34:00" },
  { en: "Saba", ar: "سبأ", translation: "Sheba", urdu: "سبا", verses: 54, type: "Meccan", benefits: "Protection from harms for the entire night and day.", duration: "21:00" },
  { en: "Fatir", ar: "فاطر", translation: "The Originator", urdu: "پیدا کرنے والا", verses: 45, type: "Meccan", benefits: "Dynamic opening of doors of Jannah on Judgment day.", duration: "20:00" },
  { en: "Ya-Sin", ar: "يس", translation: "Ya-Seen", urdu: "یسین", verses: 83, type: "Meccan", benefits: "The Heart of the Quran. Forgiveness of sins and ease of death.", duration: "18:00" },
  { en: "As-Saffat", ar: "الصافات", translation: "Those Who Set the Ranks", urdu: "صفیں باندھنے والے", verses: 182, type: "Meccan", benefits: "Saves from all pests and standard calamities.", duration: "28:00" },
  { en: "Sad", ar: "ص", translation: "The Letter Sad", urdu: "صاد", verses: 88, type: "Meccan", benefits: "Prevents from minor sins and grants heavy rewards.", duration: "21:00" },
  { en: "Az-Zumar", ar: "الزمر", translation: "The Troops", urdu: "گروہ", verses: 75, type: "Meccan", benefits: "Respect, honor in society, and grants self-reliance.", duration: "30:00" },
  { en: "Ghafir", ar: "غافر", translation: "The Forgiver", urdu: "بخشنے والا", verses: 85, type: "Meccan", benefits: "Forgives past sins and keeps heart stable on faith.", duration: "31:00" },
  { en: "Fussilat", ar: "فصلت", translation: "Explained in Detail", urdu: "تفصیل سے بیان کی گئی", verses: 54, type: "Meccan", benefits: "A light of guidance, cures eye-sight issues.", duration: "21:00" },
  { en: "Ash-Shura", ar: "الشورى", translation: "The Consultation", urdu: "مشورہ", verses: 53, type: "Meccan", benefits: "Safety on journey and protection from sudden death.", duration: "21:00" },
  { en: "Az-Zukhruf", ar: "الزخرف", translation: "The Ornaments of Gold", urdu: "زینت", verses: 89, type: "Meccan", benefits: "Safety from squeezing of the grave, peace in transition.", duration: "21:05" },
  { en: "Ad-Dukhan", ar: "الدخان", translation: "The Smoke", urdu: "دھواں", verses: 59, type: "Meccan", benefits: "Forgiveness of past sins, protection from Hellfire.", duration: "11:50" },
  { en: "Al-Jathiyah", ar: "الجاثية", translation: "The Crouching", urdu: "گھٹنوں کے بل گری ہوئی", verses: 37, type: "Meccan", benefits: "Safety from the horrific terror of Judgment Day.", duration: "13:20" },
  { en: "Al-Ahqaf", ar: "الأحقاف", translation: "The Wind-Curved Sandhills", urdu: "ریت کے ٹیلے", verses: 35, type: "Meccan", benefits: "Love of parents, safety from worldly and grave trials.", duration: "17:40" },
  { en: "Muhammad", ar: "محمد", translation: "Muhammad", urdu: "محمد صلی اللہ علیہ وسلم", verses: 38, type: "Medinan", benefits: "Thirst quenched from Jannah, safety from doubts.", duration: "14:15" },
  { en: "Al-Fath", ar: "الفتح", translation: "The Victory", urdu: "فتح", verses: 29, type: "Medinan", benefits: "Absolute victory in righteous tasks and safety.", duration: "14:50" },
  { en: "Al-Hujurat", ar: "الحجرات", translation: "The Dwellings", urdu: "حجرے", verses: 18, type: "Medinan", benefits: "Safety from enemies, peace between spouses.", duration: "09:00" },
  { en: "Qaf", ar: "ق", translation: "The Letter Qaf", urdu: "ق", verses: 45, type: "Meccan", benefits: "Sustenance multiplier, eases dying moment.", duration: "10:11" },
  { en: "Adh-Dhariyat", ar: "الذاريات", translation: "The Winnowing Winds", urdu: "بکھیرنے والی ہوائیں", verses: 60, type: "Meccan", benefits: "Easy livelihood, lights grave and cures physical pains.", duration: "10:30" },
  { en: "At-Tur", ar: "الطور", translation: "The Mount", urdu: "طور پہاڑ", verses: 49, type: "Meccan", benefits: "Release from constraints and grants happiness.", duration: "09:05" },
  { en: "An-Najm", ar: "النجم", translation: "The Star", urdu: "ستارا", verses: 62, type: "Meccan", benefits: "Grants massive respect in society and courageous heart.", duration: "09:12" },
  { en: "Al-Qamar", ar: "القمر", translation: "The Moon", urdu: "چاند", verses: 55, type: "Meccan", benefits: "Lights up the face on Resurrection Day.", duration: "09:40" },
  { en: "Ar-Rahman", ar: "الرحمن", translation: "The Beneficent", urdu: "نہایت مہربان", verses: 78, type: "Meccan", benefits: "The Bride of the Quran. Bringer of extreme blessings.", duration: "15:00" },
  { en: "Al-Waqi'ah", ar: "الواقعة", translation: "The Inevitable", urdu: "واقعہ ہونے والی", verses: 96, type: "Meccan", benefits: "Protects permanently from extreme poverty and scarcity.", duration: "11:20" },
  { en: "Al-Hadid", ar: "الحديد", translation: "The Iron", urdu: "لوہا", verses: 29, type: "Medinan", benefits: "Release from mental worries, safety from iron weapons.", duration: "16:21" },
  { en: "Al-Mujadilah", ar: "المجادلة", translation: "The Pleading Woman", urdu: "بحث کرنے والی", verses: 22, type: "Medinan", benefits: "Protection from evil eye, cures high fever.", duration: "11:10" },
  { en: "Al-Hashr", ar: "الحشر", translation: "The Exile", urdu: "حشر", verses: 24, type: "Medinan", benefits: "Seventy thousand angels pray for your forgiveness.", duration: "11:55" },
  { en: "Al-Mumtahanah", ar: "الممتحنة", translation: "She that is to be examined", urdu: "امتحان لی گئی", verses: 13, type: "Medinan", benefits: "Increases faith, purges doubts from heart.", duration: "10:10" },
  { en: "As-Saff", ar: "الصف", translation: "The Ranks", urdu: "صف", verses: 14, type: "Medinan", benefits: "Angels send salam throughout life, security on journey.", duration: "05:12" },
  { en: "Al-Jumu'ah", ar: "الجمعة", translation: "The Congregation", urdu: "جمعہ", verses: 11, type: "Medinan", benefits: "Saves from satanic influence, multiplies good deeds.", duration: "04:30" },
  { en: "Al-Munafiqun", ar: "المنافقون", translation: "The Hypocrites", urdu: "منافقین", verses: 11, type: "Medinan", benefits: "Cures internal hypocrisy, cleanses heart of doubts.", duration: "04:45" },
  { en: "At-Taghabun", ar: "التغابن", translation: "The Mutual Disillusion", urdu: "ہار جیت", verses: 18, type: "Medinan", benefits: "Intercedes at death, safety from sudden accidents.", duration: "06:12" },
  { en: "At-Talaq", ar: "الطلاق", translation: "The Divorce", urdu: "طلاق", verses: 12, type: "Medinan", benefits: "Correct path in life, ease in marital decisions.", duration: "06:00" },
  { en: "At-Tahrim", ar: "التحريم", translation: "The Prohibition", urdu: "حرام کرنا", verses: 12, type: "Medinan", benefits: "Relief from outstanding debts and sleep disorders.", duration: "06:15" },
  { en: "Al-Mulk", ar: "الملك", translation: "The Sovereignty", urdu: "بادشاہی", verses: 30, type: "Meccan", benefits: "Intercedes in the grave until forgiven, shields from grave torment.", duration: "07:30" },
  { en: "Al-Qalam", ar: "القلم", translation: "The Pen", urdu: "قلم", verses: 52, type: "Meccan", benefits: "Sharpens intellect, relief from eye strain and headaches.", duration: "08:10" },
  { en: "Al-Haqqah", ar: "الحاقة", translation: "The Inevitable Reality", urdu: "سچی ہونی والی", verses: 52, type: "Meccan", benefits: "Simplifies reckoning of faith, protects embryo in pregnancy.", duration: "08:30" },
  { en: "Al-Ma'arij", ar: "المعارج", translation: "The Ascending Stairways", urdu: "بلندیاں", verses: 44, type: "Meccan", benefits: "Saves from major sins, protects prisoner from torture.", duration: "06:40" },
  { en: "Nuh", ar: "نوح", translation: "Noah", urdu: "نوح علیہ السلام", verses: 28, type: "Meccan", benefits: "Guarantees Jannah entrance, fulfills righteous wishes.", duration: "06:12" },
  { en: "Al-Jinn", ar: "الجن", translation: "The Jinn", urdu: "جن", verses: 28, type: "Meccan", benefits: "Protects from evil jinns, evil gaze, and tyrants.", duration: "06:20" },
  { en: "Al-Muzzammil", ar: "المزمل", translation: "The Enshrouded One", urdu: "اوڑھنی لپیٹنے والا", verses: 20, type: "Meccan", benefits: "Protects from insanity, purity of soul, prayer accepted.", duration: "06:45" },
  { en: "Al-Muddaththir", ar: "المدثر", translation: "The Cloaked One", urdu: "چادر پوش", verses: 56, type: "Meccan", benefits: "Memorizing Quran becomes easy, grants wishes.", duration: "07:30" },
  { en: "Al-Qiyamah", ar: "القيامة", translation: "The Resurrection", urdu: "قیامت", verses: 40, type: "Meccan", benefits: "Easy crossing of Pul-e-Siraat, humbleness.", duration: "04:30" },
  { en: "Al-Insan", ar: "الإنسان", translation: "Man", urdu: "انسان", verses: 31, type: "Medinan", benefits: "Wins active victory in life, keeps mind clear.", duration: "06:22" },
  { en: "Al-Mursalat", ar: "المرسلات", translation: "The Emissaries", urdu: "بھیجی ہوئی ہوائیں", verses: 50, type: "Meccan", benefits: "Protects from enemies, cure from sickness.", duration: "05:40" },
  { en: "An-Naba", ar: "النبأ", translation: "The Great News", urdu: "بڑی خبر", verses: 40, type: "Meccan", benefits: "Brings energy, assists in visiting Holy Kaabah.", duration: "04:50" },
  { en: "An-Nazi'at", ar: "النازعات", translation: "Those who drag forth", urdu: "کھینچنے والے", verses: 46, type: "Meccan", benefits: "Safety on ocean journeys and tranquil end of life.", duration: "05:00" },
  { en: "Abasa", ar: "عبس", translation: "He frowned", urdu: "تیوری چڑھی", verses: 42, type: "Meccan", benefits: "Shields from sadness and shame on Resurrection Day.", duration: "03:45" },
  { en: "At-Takwir", ar: "التكوير", translation: "The Overthrowing", urdu: "لپیٹنا", verses: 29, type: "Meccan", benefits: "Cures sight issues, invokes mercy of Allah.", duration: "03:30" },
  { en: "Al-Infitar", ar: "الانفطار", translation: "The Cleaving", urdu: "پھٹنا", verses: 19, type: "Meccan", benefits: "Shield from obstacles and prison release.", duration: "03:10" },
  { en: "Al-Mutaffifin", ar: "المطففين", translation: "Defrauding", urdu: "کمی کرنے والے", verses: 36, type: "Meccan", benefits: "Safety from any punishment on the Day of Judgment.", duration: "05:15" },
  { en: "Al-Inshiqaq", ar: "الانشقاق", translation: "The Splitting Asunder", urdu: "ٹکڑے ٹکڑے ہونا", verses: 25, type: "Meccan", benefits: "Eases child-birth, protects household items.", duration: "03:20" },
  { en: "Al-Buruj", ar: "البروج", translation: "The Mansions of the Stars", urdu: "برج", verses: 22, type: "Meccan", benefits: "Keeps children safe from fright, protection in journey.", duration: "03:40" },
  { en: "At-Tariq", ar: "الطارق", translation: "The Morning Star", urdu: "صبح کا تارہ", verses: 17, type: "Meccan", benefits: "Cures physical poisoning, protects open wounds.", duration: "01:50" },
  { en: "Al-A'la", ar: "الأعلى", translation: "The Most High", urdu: "سب سے بلند", verses: 19, type: "Meccan", benefits: "Relief from earaches, memory stabilizer.", duration: "02:10" },
  { en: "Al-Ghashiyah", ar: "الغاشية", translation: "The Overwhelming", urdu: "چھا جانے والی", verses: 26, type: "Meccan", benefits: "Cures wild fears, saves from bad stomach conditions.", duration: "02:40" },
  { en: "Al-Fajr", ar: "الفجر", translation: "The Dawn", urdu: "فجر", verses: 30, type: "Meccan", benefits: "Dwells in the companionship of Prophets in Jannah.", duration: "04:12" },
  { en: "Al-Balad", ar: "البلد", translation: "The City", urdu: "شہر", verses: 20, type: "Meccan", benefits: "Cures new-born diseases, safety from anger of Allah.", duration: "02:30" },
  { en: "Ash-Shams", ar: "الشمس", translation: "The Sun", urdu: "سورج", verses: 15, type: "Meccan", benefits: "Increases memory, brings peace and popularity.", duration: "01:50" },
  { en: "Al-Layl", ar: "الليل", translation: "The Night", urdu: "رات", verses: 21, type: "Meccan", benefits: "Wipes away severe anxiety and simplifies sleep.", duration: "02:22" },
  { en: "Ad-Duha", ar: "الضحى", translation: "The Morning Hours", urdu: "ضحیٰ", verses: 11, type: "Meccan", benefits: "Finds lost assets/persons, heals depressed states.", duration: "01:30" },
  { en: "Ash-Sharh", ar: "الشرح", translation: "The Relief", urdu: "سکون", verses: 8, type: "Meccan", benefits: "Extinguishes high pressure, cures chest pain and anxiety.", duration: "00:55" },
  { en: "At-Tin", ar: "التين", translation: "The Fig", urdu: "انجیر", verses: 8, type: "Meccan", benefits: "Bettors of physical digestion, safety on voyages.", duration: "01:20" },
  { en: "Al-'Alaq", ar: "العلق", translation: "The Clot", urdu: "خون کا لوتھڑا", verses: 19, type: "Meccan", benefits: "Safety while traveling, makes study learning easy.", duration: "02:15" },
  { en: "Al-Qadr", ar: "القدر", translation: "The Power", urdu: "قدر", verses: 5, type: "Meccan", benefits: "Sins forgiven, multiplier of active righteous deeds.", duration: "00:50" },
  { en: "Al-Bayyinah", ar: "البينة", translation: "The Clear Proof", urdu: "واضح دلیل", verses: 8, type: "Medinan", benefits: "Cures swellings, makes truth clear to family.", duration: "02:20" },
  { en: "Az-Zalzalah", ar: "الزلزلة", translation: "The Earthquake", urdu: "زلزلہ", verses: 8, type: "Medinan", benefits: "Saves from fear of death, shields from lightning strikes.", duration: "01:15" },
  { en: "Al-'Adiyat", ar: "العاديات", translation: "The Courser", urdu: "دوڑنے والے", verses: 11, type: "Meccan", benefits: "Eliminates outstanding financial debts.", duration: "01:30" },
  { en: "Al-Qari'ah", ar: "القارعة", translation: "The Calamity", urdu: "کھڑکانے والی", verses: 11, type: "Meccan", benefits: "Enhances balance on Judgement Day, safety from windstorms.", duration: "01:45" },
  { en: "At-Takathur", ar: "التكاثر", translation: "The Rivalry in World Increase", urdu: "کثرت کی خواہش", verses: 8, type: "Meccan", benefits: "Saves from grave torment, recited at late afternoon.", duration: "01:25" },
  { en: "Al-'Asr", ar: "العصر", translation: "The Declining Day", urdu: "زمانہ", verses: 3, type: "Meccan", benefits: "Patience and truthfulness in life, cures fevers.", duration: "00:45" },
  { en: "Al-Humazah", ar: "الهمزة", translation: "The Slanderer", urdu: "عیب جوئی کرنے والا", verses: 9, type: "Meccan", benefits: "Protects from poverty, keeps physical health fine.", duration: "01:10" },
  { en: "Al-Fil", ar: "الفيل", translation: "The Elephant", urdu: "ہاتھی", verses: 5, type: "Meccan", benefits: "Protects from enemy attacks and bad design plans.", duration: "00:55" },
  { en: "Quraysh", ar: "قريش", translation: "Quraysh", urdu: "قریش", verses: 4, type: "Meccan", benefits: "Safeguards heart from issues, removes fear of enemy food.", duration: "01:00" },
  { en: "Al-Ma'un", ar: "الماعون", translation: "The Small Kindnesses", urdu: "معمولی نفع", verses: 7, type: "Meccan", benefits: "Allah accepts fast prayers, guarantees child blessings.", duration: "01:15" },
  { en: "Al-Kauthar", ar: "الكوثر", translation: "The Abundance", urdu: "کوثر", verses: 3, type: "Meccan", benefits: "Drink from the Pond of Kawthar, protection from enemies.", duration: "00:30" },
  { en: "Al-Kafirun", ar: "الكافرون", translation: "The Disbelievers", urdu: "کافر", verses: 6, type: "Meccan", benefits: "One quarter of Quran. Recite before sleep to secure faith.", duration: "01:10" },
  { en: "An-Nasr", ar: "النصر", translation: "The Divine Support", urdu: "مدد", verses: 3, type: "Medinan", benefits: "Equal to one quarter of Quran. Grants victory over enemies.", duration: "00:45" },
  { en: "Al-Masad", ar: "المسد", translation: "The Palm Fiber", urdu: "کھجور کے پتے کی رسی", verses: 5, type: "Meccan", benefits: "Protection from poison and bad design targets.", duration: "01:00" },
  { en: "Al-Ikhlas", ar: "الإخلاص", translation: "The Sincerity", urdu: "اخلاص", verses: 4, type: "Meccan", benefits: "One-third of Quran. Fortifies Jannah status.", duration: "00:22" },
  { en: "Al-Falaq", ar: "الفلق", translation: "The Daybreak", urdu: "فجر", verses: 5, type: "Meccan", benefits: "Divine protection from evil eye, magic, and envy.", duration: "00:30" },
  { en: "An-Nas", ar: "الناس", translation: "Mankind", urdu: "انسان", verses: 6, type: "Meccan", benefits: "Ultimate shelter against dark whispers and unseen Jinn pests.", duration: "00:35" }
];

// 30 Paras / Juz (Chapters / Parts of the Holy Quran)
const JUZ_METADATA = [
  { en: "Juz 1 (Alif Lam Meem)", ar: "الجزء الأول (آلم)", urdu: "الف لام میم", range: "Surah Al-Fatihah #1 - Surah Al-Baqarah #141", benefits: "Covers the creation, covenant with Bani Isra'eel, and changing of Qiblah." },
  { en: "Juz 2 (Sayaqool)", ar: "الجزء الثاني (سیقول)", urdu: "سیقول", range: "Surah Al-Baqarah #142 - Surah Al-Baqarah #252", benefits: "Rules on fasting, Kaabah foundation, warfare, and matrimonial laws." },
  { en: "Juz 3 (Tilkal Rusul)", ar: "الجزء الثالث (تلک الرسل)", urdu: "تلک الرسل", range: "Surah Al-Baqarah #253 - Surah Ali 'Imran #92", benefits: "Ayat-al-Kursi, trading contracts, birth of Maryam and Isa (A.S)." },
  { en: "Juz 4 (Lan Tanaloo)", ar: "الجزء الرابع (لن تنالوا)", urdu: "لن تنالوا", range: "Surah Ali 'Imran #93 - Surah An-Nisa #23", benefits: "Battle of Uhud, rules of orphanage, inheritance rights." },
  { en: "Juz 5 (Wal Muhsanat)", ar: "الجزء الخامس (والمحصنات)", urdu: "والمحصنات", range: "Surah An-Nisa #24 - Surah An-Nisa #147", benefits: "Matrimonial restrictions, prayers during travels/war, and justice." },
  { en: "Juz 6 (La Yuhibbullah)", ar: "الجزء السادس (لا یحب اللہ)", urdu: "لا یحب اللہ", range: "Surah An-Nisa #148 - Surah Al-Ma'idah #81", benefits: "Eesa (A.S.)'s ascension, treaties with People of the Book, food laws." },
  { en: "Juz 7 (Wa Iza Sami'oo)", ar: "الجزء السابع (واذا سمعوا)", urdu: "واذا سمعوا", range: "Surah Al-Ma'idah #82 - Surah Al-An'am #110", benefits: "Penalties for oaths, games of chance, creation of universe, polytheism." },
  { en: "Juz 8 (Wa Lau Annana)", ar: "الجزء الثامن (ولو اننا)", urdu: "ولو اننا", range: "Surah Al-An'am #111 - Surah Al-A'raf #87", benefits: "Dialogue with Hell and Jannah, story of Adam & Iblees, Hud (A.S)." },
  { en: "Juz 9 (Qal Al-Mala'u)", ar: "الجزء التاسع (قال الملاء)", urdu: "قال الملاء", range: "Surah Al-A'raf #88 - Surah Al-Anfal #40", benefits: "Stories of Shoaib, Musa (A.S.) & Pharaoh, rules of Battle of Badr." },
  { en: "Juz 10 (Wa'lamoo)", ar: "الجزء العاشر (واعلموا)", urdu: "واعلموا", range: "Surah Al-Anfal #41 - Surah At-Tawbah #92", benefits: "Spoils of war, battle of Hunayn, Tabuk expedition preparation." },
  { en: "Juz 11 (Ya'taziroon)", ar: "الجزء الحادي عشر (يعتذرون)", urdu: "يعتذرون", range: "Surah At-Tawbah #93 - Surah Hud #5", benefits: "Sincere repentance, story of Yunus (A.S) and Nuh (A.S.)'s ship built." },
  { en: "Juz 12 (Wa Ma Min Dabbatin)", ar: "الجزء الثاني عشر (وما من دابة)", urdu: "وما من دابة", range: "Surah Hud #6 - Surah Yusuf #52", benefits: "Detailed story of Prophet Yusuf (A.S) and his brothers." },
  { en: "Juz 13 (Wa Ma Ubabri'u)", ar: "الجزء الثالث عشر (وما ابرئ)", urdu: "وما ابرئ", range: "Surah Yusuf #53 - Surah Ibrahim #52", benefits: "Interpretation of dreams, thunder glorified, Abrahamic Duas." },
  { en: "Juz 14 (Rubama)", ar: "الجزء الرابع عشر (ربما)", urdu: "ربما", range: "Surah Al-Hijr #1 - Surah An-Nahl #128", benefits: "Guarding of Quran, the honey bee, and signs of Allah across nature." },
  { en: "Juz 15 (Subhanallazi)", ar: "الجزء الخامس عشر (سبحان الذی)", urdu: "سبحان الذی", range: "Surah Al-Isra #1 - Surah Al-Kahf #74", benefits: "The night journey (Isra), honoring parents, Al-Kahf sleeping youths." },
  { en: "Juz 16 (Qal Alam)", ar: "الجزء السادس عشر (قال الم)", urdu: "قال الم", range: "Surah Al-Kahf #75 - Surah Taha #135", benefits: "Musa & Khidr, Zulqarnain, birth of Yahya & Isa, Musa and magicians." },
  { en: "Juz 17 (Aqtaraba)", ar: "الجزء السابع عشر (اقترب)", urdu: "اقترب", range: "Surah Al-Anbya #1 - Surah Al-Hajj #78", benefits: "Prophets trials, creation of water, details of prostration of all things." },
  { en: "Juz 18 (Qad Aflaha)", ar: "الجزء الثامن عشر (قد افلح)", urdu: "قد افلح", range: "Surah Al-Mu'minun #1 - Surah Al-Furqan #20", benefits: "Traits of believers, light (Noor) ayah, purity in society." },
  { en: "Juz 19 (Wa Qalallazina)", ar: "الجزء التاسع عشر (وقال الذین)", urdu: "وقال الذین", range: "Surah Al-Furqan #21 - Surah An-Naml #55", benefits: "Solomon and queen of Sheba, ants speaking, Moses' staff magic." },
  { en: "Juz 20 (Amman Khalaqa)", ar: "الجزء العشرون (امن خلق)", urdu: "امن خلق", range: "Surah An-Naml #56 - Surah Al-'Ankabut #45", benefits: "Pharaoh's downfall, Moses' flight, patience under tests of spiders web." },
  { en: "Juz 21 (Otlu Ma Oohiya)", ar: "الجزء الحادي والعشرون (اتل ما اوحی)", urdu: "اتل ما اوحی", range: "Surah Al-'Ankabut #46 - Surah Al-Ahzab #30", benefits: "Respect of parent, Luqman's counsels, Battle of trenches." },
  { en: "Juz 22 (Wa Manyaqnut)", ar: "الجزء الثاني والعشرون (ومن یقنت)", urdu: "ومن یقنت", range: "Surah Al-Ahzab #31 - Surah Ya-Sin #27", benefits: "Wives of the Prophet, Saba's floods, angels with wings, Ya-Sin call." },
  { en: "Juz 23 (Wa Mali)", ar: "الجزء الثالث والعشرون (وما لی)", urdu: "وما لی", range: "Surah Ya-Sin #28 - Surah Az-Zumar #31", benefits: "End of Ya-Sin, ranks of angels, trial of Prophet Jonas (A.S) in fish." },
  { en: "Juz 24 (Faman Azlam)", ar: "الجزء الرابع والعشرون (فمن اظلم)", urdu: "فمن اظلم", range: "Surah Az-Zumar #32 - Surah Fussilat #46", benefits: "Repentance value, angels bearing throne, invitation to pray." },
  { en: "Juz 25 (Ilahe Yuraddu)", ar: "الجزء الخامس والعشرون (الیہ یرد)", urdu: "الیہ یرد", range: "Surah Fussilat #47 - Surah Al-Jathiyah #37", benefits: "Consultation, revelation of book, smoke trial, mercy on judgment." },
  { en: "Juz 26 (Ha' Meem)", ar: "الجزء السادس والعشرون (حم)", urdu: "حم", range: "Surah Al-Ahqaf #1 - Surah Qaf #30", benefits: "Story of wind-curves, victory (Fatah), respect of Prophet, Qaf reminder." },
  { en: "Juz 27 (Qala Fama Khatbukum)", ar: "الجزء السابع والعشرون (قال فما خطبکم)", urdu: "قال فما خطبکم", range: "Surah Adh-Dhariyat #31 - Surah Al-Hadid #29", benefits: "Ar-Rahman blessings, Waqiah warnings, Hadid iron, speed of stars." },
  { en: "Juz 28 (Qad Sami'llahu)", ar: "الجزء الثامن والعشرون (قد سمع اللہ)", urdu: "قد سمع اللہ", range: "Surah Al-Mujadilah #1 - Surah At-Tahrim #12", benefits: "Exile of Banu Nadir, Friday prayer rules, hypocrites, household secrets." },
  { en: "Juz 29 (Tabarakallazi)", ar: "الجزء التاسع والعشرون (تبارک الذی)", urdu: "تبارک الذی", range: "Surah Al-Mulk #1 - Surah Al-Mursalat #50", benefits: "Torment of grave shield, pen, story of jinns, enshrouded messenger, resurrection." },
  { en: "Juz 30 (Amma Yatasa'aloon)", ar: "الجزء الثلاثون (عم يتساءلون)", urdu: "عم يتساءلون", range: "Surah An-Naba #1 - Surah An-Nas #114", benefits: "Short powerful Surahs, final judgment details, daybreak protection." }
];

// Special, Highly Requested Spiritual Duas with precise Islamic reference citations
const SPIRITUAL_DUAS: AudioItem[] = [
  {
    id: "dua_subha",
    title: "Subha ki Dua (صبح کے وقت کی مسنون دعا)",
    cardTitle: "Morning Supplication",
    arabicTitle: "دُعَاءُ الصَّبَاحِ",
    category: "dua",
    arabicText: "اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ النُّشُورُ",
    translationText: "O Allah, by You we enter the morning, by You we enter the evening, by You we live, by You we die, and to You is the resurrection.",
    translationUrdu: "اے اللہ! تیری ہی توفیق سے ہم نے صبح کی اور تیری ہی توفیق سے ہم نے شام کی، اور تیرے ہی حکم سے ہم جیتے ہیں اور تیرے ہی حکم سے ہم مرتے ہیں، اور تیری ہی طرف دوبارہ جی اٹھنا ہے۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/MorningAndEveningAdhkaar.mp3",
    duration: "27:43",
    benefits: "Reference: Sunan Abi Dawud #5068, Jami' at-Tirmidhi #3391 (Sahih). Brings daily protection and absolute safety during all morning affairs."
  } as unknown as AudioItem,
  {
    id: "dua_waking",
    title: "So k uthne ki dua (سو کر اٹھنے کی دعا)",
    cardTitle: "Waking Up Prayer",
    arabicTitle: "دُعَاءُ الِاسْتِيقَاظِ مِنَ النَّوْمِ",
    category: "dua",
    arabicText: "الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ",
    translationText: "All praise is to Allah who gave us life after He had caused us to die, and to Him is the resurrection.",
    translationUrdu: "تمام تعریفیں اللہ ہی کے لیے ہیں جس نے ہمیں مارنے (سلانے) کے بعد زندہ (بیدار) کیا اور اسی کی طرف اٹھ کھڑے ہونا ہے۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/WakingUpFromSleep.mp3",
    duration: "9:57",
    benefits: "Reference: Sahih al-Bukhari #6312, Sahih Muslim #2711. Expresses instant gratitude for being granted a new day of life and health."
  } as unknown as AudioItem,
  {
    id: "dua_eating_before",
    title: "Khana khane se pehle ki dua (کھانا کھانے سے پہلے کی دعا)",
    cardTitle: "Before Eating",
    arabicTitle: "دُعَاءُ قَبْلَ الطَّعَامِ",
    category: "dua",
    arabicText: "بِسْمِ اللَّهِ وَعَلَى بَرَكَةِ اللَّهِ",
    translationText: "In the name of Allah and upon the blessings of Allah.",
    translationUrdu: "اللہ کے نام کے ساتھ اور اللہ کی برکت پر (ہم نے کھانا شروع کیا)۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/Eating.mp3",
    duration: "1:13",
    benefits: "Reference: Al-Mustadrak al-Hakim #7084, Sunan Abi Dawud #3767. If forgotten, say 'Bismillahi awwalahu wa akhirahu' (Tirmidhi #1858)."
  } as unknown as AudioItem,
  {
    id: "dua_eating_after",
    title: "Khane k bad ki dua (کھانا کھانے کے بعد کی دعا)",
    cardTitle: "After Eating",
    arabicTitle: "دُعَاءُ بَعْدَ الطَّعَامِ",
    category: "dua",
    arabicText: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ",
    translationText: "All praise is to Allah who fed us and gave us drink and made us Muslims.",
    translationUrdu: "تمام تعریفیں اللہ के लिए हैं जिसने हमें खिलाया और पिलाया और मुसलमान बनाया۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/AfterEating.mp3",
    duration: "0:55",
    benefits: "Reference: Sunan Abi Dawud #3850, Jami' at-Tirmidhi #3457 (Hasan). Earns the pleasure of Allah and multiplies nutritional blessings."
  } as unknown as AudioItem,
  {
    id: "dua_drinking_water",
    title: "Pani pene ki dua (پانی پینے کی آداب و دعا)",
    cardTitle: "Drinking Water Supplication",
    arabicTitle: "أَدَبُ شُرْبِ الْمَاءِ",
    category: "dua",
    arabicText: "بِسْمِ اللَّهِ (شروع میں) اور الْحَمْدُ لِلَّهِ (آخر میں)",
    translationText: "Recite 'Bismillah' before drinking and say 'Alhamdulillah' after drinking.",
    translationUrdu: "پانی پینے سے پہلے 'بِسْمِ اللَّهِ' پڑھیں اور پینے کے بعد 'الْحَمْدُ لِلَّهِ' کہیں۔ پانی بیٹھ کر دائیں ہاتھ سے تین سانسوں میں پیئیں۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/OfferingADrink.mp3",
    duration: "0:31",
    benefits: "Reference: Jami' at-Tirmidhi #1885, Sahih al-Bukhari #5631. Drinking water with Sunnah manners provides active health and safety."
  } as unknown as AudioItem,
  {
    id: "dua_drinking_milk",
    title: "Doodh pene ki dua (دودھ پینے کے بعد کی دعا)",
    cardTitle: "After Drinking Milk",
    arabicTitle: "دُعَاءُ شُرْبِ اللَّبَنِ",
    category: "dua",
    arabicText: "اللَّهُمَّ بَارِكْ لَنَا فِيهِ وَزِدْنَا مِنْهُ",
    translationText: "O Allah, bless us in it and give us abundance from it.",
    translationUrdu: "اے اللہ! ہمارے لیے اس میں برکت عطا فرما اور ہمیں اس سے بھی زیادہ (دودھ) نصیب فرما۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/Eating.mp3",
    duration: "1:13",
    benefits: "Reference: Sunan Abi Dawud #3730, Jami' at-Tirmidhi #3455 (Hasan). Recommended because milk is both a food and a drink."
  } as unknown as AudioItem,
  {
    id: "dua_toilet_before",
    title: "Betal khla jane se pehle ki dua (بیت الخلاء جانے سے پہلے کی دعا)",
    cardTitle: "Before Entering Toilet",
    arabicTitle: "دُعَاءُ دُخُولِ الْخَلَاءِ",
    category: "dua",
    arabicText: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ",
    translationText: "O Allah, I seek refuge in You from the male and female devils.",
    translationUrdu: "اے اللہ! میں ناپاک جنوں اور جننیوں (خبیثوں اور خبیثنیوں) کے شر سے تیری پناہ مانگتا ہوں۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/BeforeEnteringToilet.mp3",
    duration: "0:26",
    benefits: "Reference: Sahih al-Bukhari #142, Sahih Muslim #375. Protects your physical body from demonic eyes inside private chambers."
  } as unknown as AudioItem,
  {
    id: "dua_wudu_before",
    title: "Wazu se pehle ki dua (وضو شروع کرنے سے پہلے کی دعا)",
    cardTitle: "Before Wudu",
    arabicTitle: "التَّسْمِيَةُ قَبْلَ الْوُضُوءِ",
    category: "dua",
    arabicText: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    translationText: "In the name of Allah, the Most Gracious, the Most Merciful.",
    translationUrdu: "اللہ کے نام سے شروع جو بڑا مہربان اور نہایت رحم والا ہے۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/BeforeStartingAblution.mp3",
    duration: "0:17",
    benefits: "Reference: Sunan Ibn Majah #397, Jami' at-Tirmidhi #25 (Hasan). Necessary for unlocking the complete spiritual value of purification."
  } as unknown as AudioItem,
  {
    id: "dua_after_namaz",
    title: "Namaz k bad ki dua (نماز کے بعد مانگنے کی دعا)",
    cardTitle: "After Obligatory Prayer",
    arabicTitle: "دُعَاءُ بَعْدَ الصَّلَاةِ",
    category: "dua",
    arabicText: "اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ وَشُكْرِكَ وَحُسْنِ عِبَادَتِكَ",
    translationText: "O Allah, help me in remembering You, thanking You, and worshipping You in the best manner.",
    translationUrdu: "اے اللہ! میری مدد فرما اپنا ذکر کرنے، اپنا شکر ادا کرنے اور بہترین طریقے سے اپنی عبادت کرنے پر۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/DhikrAfterPrayer.mp3",
    duration: "8:07",
    benefits: "Reference: Sunan Abi Dawud #1522, Jami' at-Tirmidhi #3407 (Sahih). Taught by Prophet Muhammad (PBUH) directly to Muadh ibn Jabal."
  } as unknown as AudioItem,
  {
    id: "dua_sleeping_new",
    title: "Sone se pehle ki dua (رات کو سونے سے پہلے کی دعا)",
    cardTitle: "Before Sleep Supplication",
    arabicTitle: "دُعَاءُ قَبْلَ النَّوْمِ",
    category: "dua",
    arabicText: "اللَّهُمَّ بِاسْمِكَ أَمُوتُ وَأَحْيَا",
    translationText: "O Allah, in Your name I die and I live.",
    translationUrdu: "اے اللہ! میں تیرے ہی نام کے ساتھ مرتا (سوتا) ہوں اور جیتا (جاگتا) ہوں۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/BeforeSleeping.mp3",
    duration: "12:36",
    benefits: "Reference: Sahih al-Bukhari #6314, Sahih Muslim #2711. Structural security around the human soul during the state of sleep."
  } as unknown as AudioItem,
  {
    id: "dua_akhirah_success",
    title: "Akhrat me kamyabi ki dua (دنیا و آخرت کی جامع بھلائی کی دعا)",
    cardTitle: "Akhirah & Dunya Success",
    arabicTitle: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً",
    category: "dua",
    arabicText: "وَمِنْهُم مَّن يَقُولُ رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
    translationText: "And of them there are some who say: 'Our Lord! Give us in this world that which is good and in the Hereafter that which is good, and save us from the torment of the Fire.'",
    translationUrdu: "اور ان میں سے کچھ ایسے بھی ہیں جو التجا کرتے ہیں: اے ہمارے پروردگار! ہمیں دنیا میں بھی بھلائی عطا فرما اور آخرت میں بھی بھلائی عطا فرما اور ہمیں دوزخ کی آگ کے عذاب سے بچا۔",
    audioUrl: "https://www.everyayah.com/data/Alafasy_128kbps/002201.mp3",
    duration: "0:11",
    benefits: "Reference: Surah Al-Baqarah [2:201] - Quranic Verse. Best, most balanced prayer encompassing complete success across both worlds."
  } as unknown as AudioItem,
  {
    id: "dua_illness_shifa",
    title: "Bimari ki shifa k liye dua (بیماری دور کرنے اور کامل صحت پانے کی مسنون دعا)",
    cardTitle: "Healing & Shifa",
    arabicTitle: "دُعَاءُ الشِّفَاءِ لِلْمَرِيضِ",
    category: "dua",
    arabicText: "أَذْهِبِ الْبَاسَ رَبَّ النَّاسِ، اشْفِ وَأَنْتَ الشَّافِي، لَا شِفَاءَ إِلَّا شِفَاؤُكَ، شِفَاءً لَا يُغَادِرُ سَقَمًا",
    translationText: "Take away the pain, O Lord of mankind, and grant healing, for You are the Healer. There is no healing but Your healing, a healing that leaves no disease.",
    translationUrdu: "اے لوگوں کے پروردگار! تکلیف کو دور کر دے، شفا عطا فرما، تو ہی شفا دینے والا ہے۔ تیری شفا کے سوا کوئی شفا نہیں، ایسی شفا دے جو کسی قسم کی بیماری کو باقی نہ چھوڑے۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/FeelingPainInTheBody.mp3",
    duration: "0:54",
    benefits: "Reference: Sahih al-Bukhari #5743, Sahih Muslim #2191. Standard prophetic formula recited or blown on water/illnesses."
  } as unknown as AudioItem,
  {
    id: "dua_evil_eye_shield",
    title: "Nazre bad se bachao ki dua (نظرِ بد اور حاسدوں کی بری نظر سے بچنے کا مسنون حصار)",
    cardTitle: "Evil Eye Shield",
    arabicTitle: "أُعِيذُكُمَا بِكَلِمَاتِ اللَّهِ",
    category: "dua",
    arabicText: "أُعِيذُكُمَا بِكَلِمَاتِ اللَّهِ التَّامَّةِ مِنْ كُلِّ شَيْطَانٍ وَهَامَّةٍ، وَمِنْ كُلِّ عَيْنٍ لَامَّةٍ",
    translationText: "I seek protection for you both in the perfect words of Allah from every devil, poisonous pest, and from every harmful, envious, evil eye.",
    translationUrdu: "میں تم دونوں کو اللہ تعالیٰ کے کامل کلمات کی پناہ میں دیتا ہوں ہر شیطان، زہریلے کیڑے مکوڑے اور نقصان پہنچانے والی بری (حاسد) نظر سے۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/PlacingChildrenUnderProtectionOfAllaah.mp3",
    duration: "0:22",
    benefits: "Reference: Sahih al-Bukhari #3371. Daily shield used by Prophet Muhammad (PBUH) upon Hasan and Husayn (A.S)."
  } as unknown as AudioItem,
  {
    id: "dua_sudden_calamities",
    title: "Naghani aafat se bacne ki dua (ناگہانی آفات، آفات اور حادثات سے بچاؤ کی دعا)",
    cardTitle: "Sudden Calamity Shield",
    arabicTitle: "إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ الرَّاجِعُونَ",
    category: "dua",
    arabicText: "إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ، اللَّهُمَّ أْجُرْنِي فِي مُصِيبَتِي وَأَخْلِفْ لِي خَيْرًا مِنْهَا",
    translationText: "We belong to Allah and to Him we shall return. O Allah, reward me in my affliction and replace it with something better.",
    translationUrdu: "ہم اللہ ہی کے ہیں اور اسی کی طرف لوٹ کر جانے والے ہیں۔ اے اللہ! مجھے میری مصیبت میں عیوض (اجر) عطا فرما اور مجھے اس سے بہتر نعم البدل عطا فرما۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/AfflictedByACalamity.mp3",
    duration: "0:36",
    benefits: "Reference: Sahih Muslim #918. Recited when hit by any trial, sudden loss, accident, or calamity. Invokes Allah's compensation with a better blessing."
  } as unknown as AudioItem,
  {
    id: "dua_rain",
    title: "Barish ki dua (بارش برسنے کے دوران پڑھنے کی دعا)",
    cardTitle: "Dua During Rain",
    arabicTitle: "دُعَاءُ نُزُولِ الْمَطَرِ",
    category: "dua",
    arabicText: "اللَّهُمَّ صَيِّبًا نَافِعًا",
    translationText: "O Allah, may it be a beneficial rain.",
    translationUrdu: "اے اللہ! اس برستی ہوئی بارش کو ہمارے لیے نفع بخش اور خوب رحمت کا سبب بنا دے۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/WhenItRains.mp3",
    duration: "0:26",
    benefits: "Reference: Sahih al-Bukhari #1032. Rain is an awesome answer period. Reciting this invites grace and prevents crop/city flooding dangers."
  } as unknown as AudioItem
];

const WAZAIF_DATA: AudioItem[] = [
  {
    id: "azkar_after_namaz",
    title: "Namaz k bad k azkar (نماز کے بعد پڑھنے کے مسنون اذکار)",
    cardTitle: "Post-Salah Azkar List",
    arabicTitle: "الْأَذْكَارُ بَعْدَ الصَّلَاةِ",
    category: "wird",
    arabicText: "أَسْتغْفِرُ اللَّهَ (3x)، اللَّهُمَّ أَنْتَ السَّلَامُ... سُبْحَانَ اللَّهِ (33x)، الْحَمْدُ لِلَّهِ (33x)، اللَّهُ أَكْبَرُ (34x)",
    translationText: "I seek Allah's forgiveness (3x). O Allah, You are Peace and from You comes peace... SubhanAllah (33x), Alhamdulillah (33x), Allahu Akbar (34x).",
    translationUrdu: "میں اللہ سے مغفرت مانگتا ہوں (3 بار)۔ اے اللہ! تو ہی سلامتی والا ہے اور تیری ہی طرف سے سلامتی ہے۔ تو برکت والا ہے۔۔۔ پھر 33 بار سبحان اللہ، 33 بار الحمدللہ، 34 بار اللہ اکبر پڑھیں۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/DhikrAfterPrayer.mp3",
    duration: "8:07",
    benefits: "Reference: Sahih Muslim #591, Sahih al-Bukhari #843. Cleanses minor imperfections during the prayer units and multiplies deeds immensely."
  } as unknown as AudioItem,
  {
    id: "azkar_rizq_increase",
    title: "Rizak me izafe k azkar (کاروباری ترقی، مالی برکت اور وسعتِ رزق کا وظیفہ)",
    cardTitle: "Sustenance Expansion",
    arabicTitle: "الْأَذْكَارُ لِتَوْسِيعِ الرِّزْقِ",
    category: "wird",
    arabicText: "لَا إِلٰهَ إِلَّا اللّٰهُ الْمَلِکُ الْحَقُّ الْمُبِینُ (١٠٠ بار روزانہ بعدِ ظہر) یا کثرت سے 'يَا رَزَّاقُ'",
    translationText: "Recite 'La ilaha illa Allah, al-Malik, al-Haqq, al-Mubeen' 100 times daily after Zuhr prayer, and chant 'Ya Razzaqu' excessively.",
    translationUrdu: "روزانہ ظہر کی نماز کے بعد 'لَا إِلٰهَ إِلَّا اللّٰهُ الْمَلِکُ الْحَقُّ الْمُبِینُ' 100 مرتبہ پڑھیں، اور صبح و شام کثرت سے 'یَا رَزَّاقُ' پڑھیں۔ یہ عمل تنگی دور کرتا ہے اور رزق کے بند دروازے کھولتا ہے۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/PayingADebt.mp3",
    duration: "4:01",
    benefits: "Reference: Jami' al-Sagheer (Al-Suyuti) / Al-Khatib Al-Baghdadi #1030. Acts as a magnificent magnet for unexpected, pure financial resources."
  } as unknown as AudioItem,
  {
    id: "azkar_poverty_shield",
    title: "Tangdasti se bachao k azkar (فقر اور معاشی محتاجی سے سچی حفاظت کا ورد)",
    cardTitle: "Avoid Scarcity",
    arabicTitle: "أَذْكَارُ النَّجَاةِ مِنَ الْفَقْرِ",
    category: "wird",
    arabicText: "لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ الْعَلِيِّ الْعَظِيمِ (١٠٠ بار روزانہ)",
    translationText: "There is no power nor strength except with Allah, the Most High, the Most Great (Recommended to recite 100 times daily for relief).",
    translationUrdu: "روزانہ بلا ناغہ سو مرتبہ 'لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ الْعَلِيِّ الْعَظِيمِ' پڑھیں۔ اس سے فقر، تنگدستی، معاشی رکاوٹیں اور ستر قسم کی پوشیدہ بلائیں دور رہتی ہیں۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/AffairsHaveBecomeDifficult.mp3",
    duration: "0:25",
    benefits: "Reference: Al-Mu'jam al-Awsat (Tabarani), Sahih al-Bukhari #30. Out of the treasures of Paradise. Eradicates distress, debt pressure, and deep worldly dependencies."
  } as unknown as AudioItem,
  {
    id: "azkar_lost_item",
    title: "Gumshuda cheez k liye azkar (کھوئی ہوئی قیمتی چیز پانے کا مانا ہوا عمل)",
    cardTitle: "Finding Lost Property",
    arabicTitle: "أَذْكَارُ رَدِّ الضَّالَّةِ",
    category: "wird",
    arabicText: "يَا جَامِعَ النَّاسِ لِيَوْمٍ لَا رَيْبَ فِيهِ إِنَّ اللَّهَ لَا يُخْلِفُ الْمِيعَادَ، اِجْمَعْ بَيْنِي وَبَيْنَ ضَالَّتِي (١١٩ بار)",
    translationText: "O Gatherer of mankind on a Day about which there is no doubt, collect and return my lost property to me.",
    translationUrdu: "باوضو حالت میں 119 مرتبہ 'يَا جَامِعَ النَّاسِ...' اور 'اِجْمَعْ بَيْنِي وَبَيْنَ ضَالَّتِي' کو کثرت سے پڑھیں۔ یہ اسلاف کا مانا ہوا نہایت تیز ترین مجرب وظیفہ ہے۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/WhenInDistress.mp3",
    duration: "0:56",
    benefits: "Reference: Al-Dua by Imam Al-Tabarani / Sharh Ihya (Imam Al-Ghazaliؒ). Calms the anxious heart and miraculously opens avenues to trace stolen or lost articles."
  } as unknown as AudioItem,
  {
    id: "azkar_magic_protection",
    title: "Jado se bachao k liye azkar (کالے جادو اور سفلی شیطانوں کی پکی کاٹ)",
    cardTitle: "Magic & Sorcery Shield",
    arabicTitle: "أَذْكَارُ قَمْعِ السِّحْرِ",
    category: "wird",
    arabicText: "لَا إِلٰهَ إِلَّا اللّٰهُ وَحْدَهُ لَا شَرِیکَ لَهُ، لَهُ الْمُلْکُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ (١٠٠ بار روزانہ)",
    translationText: "There is no god but Allah, alone without partner. His is the kingdom, and His is the praise, and He has power over all things.",
    translationUrdu: "صبح و شام سو (100) مرتبہ اس کملے کا ورد ہر قسم کے جادو ٹونے، سفلی اثرات، بد نظر زہریلی روحوں سے بچاؤ کا ناقابل شکست آہنی قلعہ ہے۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/ToWardOffShayateen.mp3",
    duration: "1:22",
    benefits: "Reference: Sahih al-Bukhari #3293, Sahih Muslim #2691. Cures long-standing occult blocks in work, business, marriage, and family health structures."
  } as unknown as AudioItem,
  {
    id: "azkar_maooz_teen",
    title: "Maooz teen - jadoo k liye (معوذتین - جادو، بندش اور جنات کی زبردست کاٹ)",
    cardTitle: "The Three Quls Shield",
    arabicTitle: "الْمُعَوِّذَاتُ الثِّلَاثَةُ لِلسِّحْرِ",
    category: "wird",
    arabicText: "سُورَةُ الْإِخْلَاصِ ۝ سُورَةُ الْفَلَقِ ۝ سُورَةُ النَّاسِ (تین تین بار صبح و شام تلاوت کریں)",
    translationText: "Recite Surah Al-Ikhlas, Surah Al-Falaq, and Surah An-Nas 3 times each, blowing over your hands and wiping your full body.",
    translationUrdu: "روزانہ فجر اور مغرب کے وقت ان تینوں سورتوں کو 3 بار پڑھ کر پورے گھر کے کونوں اور اپنے جسم پر پھونکیں۔ ہر قسم کا کالا جادو خاکستر ہو جائے گا۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/ExpellingShaytaan.mp3",
    duration: "0:45",
    benefits: "Reference: Jami' at-Tirmidhi #3439, Sunan Abi Dawud #5082 (Sahih). Best divine antidote against dark curses, complex magical knots, and envious enemies."
  } as unknown as AudioItem,
  {
    id: "azkar_hizb_al_bahr",
    title: "Dua Hizbal Bahr (دعائے حزب البحر شریف - امام ابو الحسن شاذلیؒ)",
    cardTitle: "The Sea Litany",
    arabicTitle: "دُعَاءُ حِزْبِ الْبَحْرِ",
    category: "wird",
    arabicText: "يَا عَلِيُّ يَا عَظِيمُ يَا حَلِيمُ يَا عَلِيمُ أَنْتَ رَبِّي وَعِلْمُكَ حَسْبِي... تَنْصُرُ مَنْ تَشَاءُ وَأَنْتَ الْعَزِيزُ الرَّحِيمُ",
    translationText: "The Complete Majestic Litany of the Sea by Imam Shadhili. Unbeatable spiritual shield recited to dismantle occult activities, plots, and major worldly restrictions.",
    translationUrdu: "دعائے حزب البحر مبارک جو آفات و بلیات، دشمنوں کے وار، حاسدین کے حسد، بندشوں اور کٹھن حالات سے نجات کا لاجواب اور مانا ہوا آزمودہ نورانی علاج ہے۔",
    audioUrl: "https://archive.org/download/hizbulbahr_202003/HizbulBahr.mp3",
    duration: "7:02",
    benefits: "Reference: major classical litany (منظومہ حصار شاذلیہ) validated by centuries of spiritual masters. Purifies heart blocks and secures ultimate material safety."
  } as unknown as AudioItem,
  {
    id: "azkar_ayat_ul_kursi",
    title: "Ayatl kursi (آیت الکرسی - کائنات کی سب سے عظیم ترین سورت و تسبیح)",
    cardTitle: "The Throne Verse",
    arabicTitle: "آيَةُ الْكُرْسِيِّ",
    category: "wird",
    arabicText: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ...",
    translationText: "Allah! There is no deity except Him, the Ever-Living, the Sustainer of all existence. Neither drowsiness overtakes Him nor sleep.",
    translationUrdu: "اللہ، اس کے سوا کوئی معبود نہیں، وہ ہمیشہ زندہ اور کائنات کا نگہبان ہے۔ اسے نہ پیگھونگی آتی ہے نہ نیند۔ جو کچھ زمین و آسمان میں ہے سب اسی کا ہے۔۔",
    audioUrl: "https://www.everyayah.com/data/Alafasy_128kbps/002255.mp3",
    duration: "1:35",
    benefits: "Reference: Sahih al-Bukhari #2311, Sahih Muslim #810. Reciting it once before sleeping assigns a golden guardian angel from Allah to protect you until morning."
  } as unknown as AudioItem
];

const SIX_KALMA_DATA: AudioItem[] = [
  {
    id: "kalma_1",
    title: "First Kalma - Tayyabah (پہلا کلمہ - طیب)",
    cardTitle: "1st Kalma (Tayyabah)",
    arabicTitle: "الْكَلِمَةُ الطَّيِّبَة",
    category: "kalma",
    arabicText: "لَا إِلٰهَ إِلَّا اللّٰهُ مُحَمَّدٌ رَّسُولُ اللّٰهِ",
    translationText: "There is no deity except Allah; Muhammad is the Messenger of Allah.",
    translationUrdu: "اللہ کے سوا کوئی معبود نہیں، حضرت محمد (صلی اللہ علیہ وسلم) اللہ کے سچے رسول ہیں۔",
    audioUrl: "https://archive.org/download/6th-qalma-radde-kufr/1st-Qalma-Tayyab.mp3",
    duration: "0:12",
    benefits: "Reference: Sahih al-Bukhari #8. The primary baseline foundation of entering the folds of Islam. Reciting it cleanses the spiritual heart."
  } as unknown as AudioItem,
  {
    id: "kalma_2",
    title: "Second Kalma - Shahadah (دوسرا کلمہ - شہادت)",
    cardTitle: "2nd Kalma (Shahadah)",
    arabicTitle: "كَلِمَةُ الشَّهَادَةِ",
    category: "kalma",
    arabicText: "أَشْهَدُ أَنْ لَّا إِلٰهَ إِلَّا اللّٰهُ وَحْدَهُ لَا شَرِيكَ لَهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ",
    translationText: "I bear witness that there is no deity except Allah, the One, without partner; and I bear witness that Muhammad is His servant and Messenger.",
    translationUrdu: "میں گواہی دیتا ہوں کہ اللہ کے سوا کوئی معبود نہیں، وہ اکیلا ہے، اس کا کوئی شریک نہیں، اور میں گواہی دیتا ہوں کہ حضرت محمد (صلی اللہ علیہ وسلم) اللہ کے سچے بندے اور رسول ہیں۔",
    audioUrl: "https://archive.org/download/6th-qalma-radde-kufr/2nd-Qalma-Shahada.mp3",
    duration: "0:18",
    benefits: "Reference: Sahih Muslim #234. Reciting it precisely after performing complete and perfect Wudu unlocks all eight majestic gates of Paradise for your entry."
  } as unknown as AudioItem,
  {
    id: "kalma_3",
    title: "Third Kalma - Tamjeed (تیسرا کلمہ - تمجید)",
    cardTitle: "3rd Kalma (Tamjeed)",
    arabicTitle: "كَلِمَةُ التَّمْجِيدِ",
    category: "kalma",
    arabicText: "سُبْحَانَ اللّٰهِ وَالْحَمْدُ لِلّٰهِ وَلَا إِلٰهَ إِلَّا اللّٰهُ وَاللّٰهُ أَكْبَرُ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللّٰهِ الْعَلِيِّ الْعَظِيمِ",
    translationText: "Glory be to Allah, and praise be to Allah, and there is no deity except Allah, and Allah is the Greatest; and there is no power nor strength except with Allah, the Most High, the Most Great.",
    translationUrdu: "پاک ہے اللہ، اور تمام تعریفیں اللہ ہی کے لیے ہیں، اور اللہ کے سوا کوئی معبود نہیں، اور اللہ سب سے بڑا ہے، اور گناہوں سے بچنے کی ہمت اور نیک کام کرنے کی طاقت اللہ ہی کی طرف سے ہے جو بلند مرتبہ اور عظمت والا ہے۔",
    audioUrl: "https://archive.org/download/6th-qalma-radde-kufr/3rd-Qalma-Tamjeed.mp3",
    duration: "0:25",
    benefits: "Reference: Sunan At-Tirmidhi #3460, Jami' at-Tirmidhi #3509. Known as the 'Al-Baqiyat al-Salihat' (The Everlasting Good Deeds). Brings magnificent peace."
  } as unknown as AudioItem,
  {
    id: "kalma_4",
    title: "Fourth Kalma - Tauheed (چوتھا کلمہ - توحید)",
    cardTitle: "4th Kalma (Tauheed)",
    arabicTitle: "كَلِمَةُ التَّوْحِيدِ",
    category: "kalma",
    arabicText: "لَا إِلٰهَ إِلَّا اللّٰهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، يُحْيِي وَيُمِيتُ وَهُوَ حَيٌّ لَّا يَمُوتُ أَبَدًا أَبَدًا، ذُو الْجَلَالِ وَالْإِكْرَامِ، بِيَدِهِ الْخَيْرُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
    translationText: "There is no deity except Allah, alone without partner. His is the sovereignty and His is the praise. He gives life and causes death, and He is Ever-Living, He never dies. Possessor of majesty and honor. In His hand is goodness, and He is power over all things.",
    translationUrdu: "اللہ کے سوا کوئی معبود نہیں، وہ اکیلا ہے، اس کا کوئی شریک نہیں۔ اسی کی بادشاہی ہے اور اسی کے لیے تمام تعریفیں ہیں۔ وہی جلاتا ہے اور وہی مارتا ہے، اور وہ ہمیشہ زندہ ہے، کبھی نہیں مرے گا۔ وہ عظمت اور بزرگی والا ہے۔ اس کے ہاتھ میں بھلائی ہے اور وہ ہر چیز پر قادر ہے۔",
    audioUrl: "https://archive.org/download/6th-qalma-radde-kufr/4th-Qalma-Tawheed.mp3",
    duration: "0:35",
    benefits: "Reference: Jami' at-Tirmidhi #3428 (Sahih). Reciting this fourth Kalma while entering marketplace deletes a million sins, writes a million rewards, and raises status."
  } as unknown as AudioItem,
  {
    id: "kalma_5",
    title: "Fifth Kalma - Astaghfar (پانچواں کلمہ - استغفار)",
    cardTitle: "5th Kalma (Astaghfar)",
    arabicTitle: "كَلِمَةُ الاسْتِغْفَارِ",
    category: "kalma",
    arabicText: "أَسْتَغْفِرُ اللّٰهَ رَبِّي مِنْ كُلِّ ذَنْبٍ أَذْنَبْتُهُ عَمَدًا أَوْ خَطَأً سِرًّا أَوْ عَلَانِيَةً وَأَتُوبُ إِلَيْهِ مِنَ الذَّنْبِ الَّذِي أَعْلَمُ وَمِنَ الذَّنْبِ الَّذِي لَا أَعْلَمُ، إِنَّكَ أَنْتَ عَلَّامُ الْغُيُوبِ وَسَتَّارُ الْعُيُوبِ وَغَفَّارُ الذُّنُوبِ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ الْعَلِيِّ الْعَظِيمِ",
    translationText: "I seek forgiveness from Allah, my Lord, for every sin I committed, knowingly or unknowingly, secretly or openly, and I turn to Him in repentance from the sin I know and from the sin I do not know... Indeed, You are the Knower of hidden things.",
    translationUrdu: "میں اللہ سے معافی مانگتا ہوں جو میرا رب ہے اپنے ہر اس گناہ سے جو میں نے جان بوجھ کر کیا یا بھول کر، پوشیدہ کیا یا اعلانیہ، اور میں اس کی بارگاہ میں توبہ کرتا ہوں اس گناہ سے جو مجھے یاد ہے اور اس گناہ سے جو مجھے یاد نہیں۔ بے شک تو غیبوں کا خوب جاننے والا ہے، اور عیبوں کا چھپانے والا اور گناہوں کا بخشنے والا ہے۔۔۔",
    audioUrl: "https://archive.org/download/6th-qalma-radde-kufr/5th-Qalma-Istighfar.mp3",
    duration: "0:45",
    benefits: "Reference: Surah Nuh [71:10-12] / Sunan Ibn Majah #4250. Seeking sincere Istighfar deletes material blockades, grants child blessings, and rains infinite sustenance."
  } as unknown as AudioItem,
  {
    id: "kalma_6",
    title: "Sixth Kalma - Rad-de-Kufr (چھٹا کلمہ - ردِ کفر)",
    cardTitle: "6th Kalma (Rad-de-Kufr)",
    arabicTitle: "كَلِمَةُ رَدِّ الْكُفْرِ",
    category: "kalma",
    arabicText: "الَّلهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ أَنْ أُشْرِكَ بِكَ شَيْئًا وَأَنَا أَعْلَمُ بِهِ، وَأَسْتَغْفِرُكَ لِمَا لَا أَعْلَمُ بِهِ، تُبْتُ عَنْهُ وَتَبَرَّأْتُ مِنَ الْكُفْرِ وَالشِّرْکِ وَالْکَذِبِ وَالْغِيبَةِ وَالْبِدْعَةِ وَالنَّمِيمَةِ وَالْفَوَاحِشِ وَالْبُهْتَانِ وَالْمَعَاصِي كُلِّهَا، وَأَسْلَمْتُ وَأَقُولُ لَا إِلٰهَ إِلَّا اللّٰهُ مُحَمَّدٌ رَّسُولُ اللّٰهِ",
    translationText: "O Allah! I seek refuge in You from associating anything with You while I know it, and seek Your forgiveness for what I do not know. I repent from it and free myself from disbelief, polytheism, lying, backbiting, innovation, slander, lewdness, and all disobedience...",
    translationUrdu: "اے اللہ! میں تیری پناہ مانگتا ہوں اس بات سے کہ میں کسی چیز کو دانستہ تیرا شریک بناؤں، اور معافی مانگتا ہوں اس گناہ سے جس کو میں نہیں جانتا۔ میں نے اس شرک سے سچی توبہ کی اور الگ ہوا کفر, شرک، جھوٹ، غیبت، بدعت، چغلی، فحش کاموں، بہتان اور تمام گناہوں سے۔۔۔",
    audioUrl: "https://archive.org/download/6th-qalma-radde-kufr/6th-Qalma-Radde%20Kufr.mp3",
    duration: "1:24",
    benefits: "Reference: Musnad Ahmad #19163 / Al-Adab Al-Mufrad. A powerful shield to root out hidden hypocrisy, doubt, false vanity, and internal anxiety of faith."
  } as unknown as AudioItem
];

const CHILDREN_NAMAZ_DATA: AudioItem[] = [
  {
    id: "namaz_step_1",
    title: "Step 1: Niyyah & Takbeer-e-Tahreemah (نیت اور تکبیرِ تحریمہ)",
    cardTitle: "Step 1: Start Prayer",
    arabicTitle: "بِدَايَةُ الصَّلَاةِ — تَكْبِيرُ",
    category: "children",
    arabicText: "اللَّهُ أَكْبَرُ",
    translationText: "Allah is the Greatest (Allahu Akbar). Action: Stand straight, raise both hands to ears (boys) or shoulders (girls), and declare Niyyah.",
    translationUrdu: "تفصیلی طریقہ: قبلہ رو سیدھے کھڑے ہو جائیں۔ نیت کریں، پھر دونوں ہاتھ کانوں کے برابر لے جا کر 'اللَّهُ أَكْبَرُ' کہتے ہوئے ناف کے نیچے باندھ لیں (لڑکے) یا سینے پر رکھیں (لڑکیاں)۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/DuringTheAdhaan.mp3",
    duration: "0:08",
    benefits: "Children's Namaz Guide: Standard procedure compiled from Sahih Muslim #390. This step locks connection with the worldly matters and directs focus purely to Allah."
  } as unknown as AudioItem,
  {
    id: "namaz_step_2",
    title: "Step 2: Sanaa - Opening Supplication (ثنا - نماز کا آغاز)",
    cardTitle: "Step 2: Sanaa Recitation",
    arabicTitle: "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ",
    category: "children",
    arabicText: "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ وَتَبَارَكَ اسْمُكَ وَتَعَالَى جَدُّكَ وَلَا إِلَهَ غَيْرُكَ",
    translationText: "Glory be to You, O Allah, and praise be to You, and blessed is Your name, and exalted is Your majesty, and there is no deity besides You.",
    translationUrdu: "پاک ہے تو اے اللہ! اور تیرے ہی لیے تمام تعریفیں ہیں، اور تیرا نام بڑا بابرکت ہے، اور تیری بزرگی بہت برتر ہے، اور تیرے سوا کوئی بندگی کے لائق معبود نہیں۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/StartOfThePrayer-AfterTakbeer.mp3",
    duration: "0:15",
    benefits: "Children's Namaz Guide: Recited in quiet audible mode under Hanafi and general majority Sunnah covenants. Reference: Sunan Abi Dawud #775."
  } as unknown as AudioItem,
  {
    id: "namaz_step_3",
    title: "Step 3: Surah Al-Fatihah (سورہ فاتحہ کی لازمی تلاوت)",
    cardTitle: "Step 3: Surah Al-Fatihah",
    arabicTitle: "بِسْمِ اللَّهِ ۝ الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ",
    category: "children",
    arabicText: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ ۝ الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ ۝ الرَّحْمَٰنِ الرَّحِيمِ ۝ مَالِكِ يَوْمِ الدِّينِ ۝ إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ ۝ اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ ۝ صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ",
    translationText: "In the name of Allah... All praise is due to Allah, Lord of the worlds... Guide us to the straight path...",
    translationUrdu: "اللہ کے نام سے شروع جو بڑا مہربان اور نہایت رحم والا ہے۔ تمام تعریفیں اللہ کے لیے ہیں جو تمام جہانوں کا پالنے والا ہے۔۔۔ ہمیں سیدھی راہ پر چلا۔۔۔",
    audioUrl: "https://server8.mp3quran.net/afs/001.mp3",
    duration: "0:45",
    benefits: "Children's Namaz Guide: Essential pillar. Recited in every single unit of Salah. Reference: Sahih al-Bukhari #756 (There is no complete Salah without Al-Fatihah)."
  } as unknown as AudioItem,
  {
    id: "namaz_step_4",
    title: "Step 4: Reciting another Surah (سورت ملانا - سورہ اخلاص)",
    cardTitle: "Step 4: Add Surah Al-Ikhlas",
    arabicTitle: "قُلْ هُوَ اللَّهُ أَحَدٌ",
    category: "children",
    arabicText: "قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ",
    translationText: "Say, 'He is Allah, the One. Allah, the Eternal Refuge. He neither begets nor is He begotten, and there is none co-equal to Him.'",
    translationUrdu: "آپ فرما دیجئے: وہ اللہ اکیلا ہے۔ اللہ بے نیاز (سب کا ملجا ومادی) ہے۔ نہ اس کی کوئی اولاد ہے اور نہ وہ کسی کی اولاد ہے۔ اور اس کا کوئی ہمسر نہیں۔",
    audioUrl: "https://server8.mp3quran.net/afs/112.mp3",
    duration: "0:12",
    benefits: "Children's Namaz Guide: For learners, one short Surah is recited after Surah Al-Fatihah in the first two units/Rakaats of Fard, and all Rakaats of Sunnah/Nafl."
  } as unknown as AudioItem,
  {
    id: "namaz_step_5",
    title: "Step 5: Ruku - Bending posture (رکوع کی تسبیح پڑھنے کا طریقہ)",
    cardTitle: "Step 5: Ruku (Bowing)",
    arabicTitle: "سُبْحَانَ رَبِّيَ الْعَظِيمِ (٣ بار)",
    category: "children",
    arabicText: "سُبْحَانَ رَبِّيَ الْعَظِيمِ",
    translationText: "Glory be to my Lord, the Magnificent (Recited 3 times). Action: Bend at waist, keep back parallel to ground, and hold knees with fingers spread.",
    translationUrdu: "تفصیلی طریقہ: 'اللَّهُ أَكْبَرُ' کہتے ہوئے رکوع میں جھک جائیں۔ نظریں پیروں کے انگوٹھوں پر رکھیں۔ پھر کم از کم 3 مرتبہ 'سُبْحَانَ رَبِّيَ الْعَظِيمِ' کہیں۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/InRukoo-Bowing.mp3",
    duration: "0:12",
    benefits: "Children's Namaz Guide: Cites absolute submission. Reference: Sahih Muslim #482. Keeps bodily spine aligned and models humbleness."
  } as unknown as AudioItem,
  {
    id: "namaz_step_6",
    title: "Step 6: Qiyam - Standing posture (رکوع سے سیدھے کھڑے ہونا)",
    cardTitle: "Step 6: Standing Straight",
    arabicTitle: "سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ",
    category: "children",
    arabicText: "تسمیع: سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ — تحمید: رَبَّنَا لَكَ الْحَمْدُ",
    translationText: "Allah hears those who praise Him (Sami' Allahu Liman Hamidah). Our Lord, to You belongs all praise (Rabbana Lakal Hamd). Stand straight.",
    translationUrdu: "سیدھے کھڑے ہوتے ہوئے 'سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ' کہیں، جب مکمل سیدھے کھڑے ہو جائیں تو کہیں 'رَبَّنَا لَكَ الْحَمْدُ'۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/RisingFromRukoo.mp3",
    duration: "0:10",
    benefits: "Children's Namaz Guide: Standing upright and calm after bowing is absolutely necessary (termed Qawmah). Reference: Sahih al-Bukhari #789."
  } as unknown as AudioItem,
  {
    id: "namaz_step_7",
    title: "Step 7: Sajdah - First Prostration (پہلا سجدہ کرنے کا تفصیلی طریقہ)",
    cardTitle: "Step 7: First Sajdah",
    arabicTitle: "سُبْحَانَ رَبِّيَ الْأَعْلَى (٣ بار)",
    category: "children",
    arabicText: "سُبْحَانَ رَبِّيَ الْأَعْلَى",
    translationText: "Glory be to my Lord, the Most High (Recited 3 times). Action: Kneel down, press nose, forehead, palms, knees and toes against ground.",
    translationUrdu: "باری باری گھٹنے، ہاتھ، ناک اور ماتھا زمین پر رکھیں۔ قدموں کی انگلیوں کے سرے قبلہ رخ تنے ہوں۔ پھر 3 بار 'سُبْحَانَ رَبِّيَ الْأَعْلَى' کہیں۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/InSujood.mp3",
    duration: "0:15",
    benefits: "Children's Namaz Guide: The closest a believer is to Allah. Reference: Sahih Muslim #482. Stimulates mental clarity, calmness, and humility."
  } as unknown as AudioItem,
  {
    id: "namaz_step_8",
    title: "Step 8: Jalsah - Sitting between Sajdahs (دونوں سجدوں کے درمیان بیٹھنا)",
    cardTitle: "Step 8: Sit upright",
    arabicTitle: "رَبِّ اغْفِرْ لِي (٢ بار)",
    category: "children",
    arabicText: "رَبِّ اغْفِرْ لِي ، اللَّهُمَّ اغْفِرْ لِي وَارْحَمْنِي",
    translationText: "O my Lord, forgive me (Rabb-ighfir li). Action: Sit upright on left foot with right foot erect (boys) or flat on ground (girls) for a moment.",
    translationUrdu: "پہلے سجدے سے 'اللَّهُ أَكْبَرُ' کہتے ہوئے اٹھیں اور سکون سے چند سیکنڈ سیدھے بیٹھیں۔ اس دوران پڑھیں: 'رَبِّ اغْفِرْ لِي وَارْحَمْنِي'۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/BetweenTheTwoSajdah.mp3",
    duration: "0:11",
    benefits: "Children's Namaz Guide: Golden sitting state of peace between the two prostrations. Reference: Sunan Ibn Majah #897."
  } as unknown as AudioItem,
  {
    id: "namaz_step_9",
    title: "Step 9: Second Sajdah (دوسرا سجدہ اور اگلی رکعت کا آغاز)",
    cardTitle: "Step 9: Second Sajdah",
    arabicTitle: "سُبْحَانَ رَبِّيَ الْأَعْلَى (٣ بار)",
    category: "children",
    arabicText: "سُبْحَانَ رَبِّيَ الْأَعْلَى",
    translationText: "Glory be to my Lord, the Most High (Recited 3 times). Action: Repeat the exact prostration posture as the first Sajdah.",
    translationUrdu: "'اللَّهُ أَكْبَرُ' کہہ کر دوبارہ زمین پر جا کر سجدہ کریں۔ پھر 3 بار 'سُبْحَانَ رَبِّيَ الْأَعْلَى' کہیں۔ یوں ایک رکعت مکمل ہو گئی۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/InSujood.mp3",
    duration: "0:14",
    benefits: "Children's Namaz Guide: Completing second Sajdah seals one full Rakaat. Rise with 'Allahu Akbar' without taking hand supports if possible."
  } as unknown as AudioItem,
  {
    id: "namaz_step_10",
    title: "Step 10: Qa'dah - Tashahhud & Durood (قعدہ اخیرہ - تشہد و درود شریف)",
    cardTitle: "Step 10: Attahiyyat Standing Sit",
    arabicTitle: "التَّحِيَّاتُ لِلّٰهِ ۝ اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ",
    category: "children",
    arabicText: "التَّحِيَّاتُ لِلَّهِ... اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ... اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ... رَبِّ اجْعَلْنِي مُقِيمَ الصَّلَاةِ",
    translationText: "Recite Tashahhud (Salutations to Allah), Durood-e-Ibrahimi (Blessings on the Prophet), and Dua-e-Masura for final acceptance.",
    translationUrdu: "دو یا چار رکعت کے بعد التحیّات کی پوزیشن میں بیٹھ کر تشہد، پھر درودِ ابراہیمی اور آخر میں 'رَبِّ اجْعَلْنِي مُقِيمَ الصَّلَاةِ...' تلاوت کریں۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/Tashahhud.mp3",
    duration: "1:20",
    benefits: "Children's Namaz Guide: Final seating inside Salah before ending. Reference: Sahih al-Bukhari #831. Raises standard status and reviews core faith principles."
  } as unknown as AudioItem,
  {
    id: "namaz_step_11",
    title: "Step 11: Tasleem - Salam (سلام پھیرنا - نماز کا باقاعدہ اختتام)",
    cardTitle: "Step 11: Ending prayer",
    arabicTitle: "السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللَّهِ",
    category: "children",
    arabicText: "السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللَّهِ (دائیں اور بائیں طرف)",
    translationText: "Peace and mercy of Allah be upon you (Assalamu Alaykum wa Rahmatullah). Turn face right first, then left to end prayer.",
    translationUrdu: "سر کو پہلے دائیں کندھے کی طرف موڑتے ہوئے 'السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللَّهِ' کہیں، پھر بائیں کندھے کی طرف موڑ کر بھی یہی کلمات کہیں۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/ExcellenceOfSpreadingIslamicGreetings.mp3",
    duration: "0:12",
    benefits: "Children's Namaz Guide: Formal conclusion of daily prayer. Reference: Sahih Muslim #582. Sends angelic signals of peace to your organic surrounding fellows."
  } as unknown as AudioItem
];

const DAROOD_DATA: AudioItem[] = [
  {
    id: "darood_ibrahimi",
    title: "Durood-e-Ibrahimi (درودِ ابراہیمی)",
    cardTitle: "Durood-e-Ibrahimi",
    arabicTitle: "الصَّلَاةُ الْإِبْرَاهِيمِيَّة",
    category: "darood",
    arabicText: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حمِيدٌ مَجِيدٌ ۝ اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا بَارَكْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ",
    translationText: "O Allah, send prayers upon Muhammad and upon the family of Muhammad, as You sent prayers upon Abraham...",
    translationUrdu: "اے اللہ! محمد (صلی اللہ علیہ وسلم) اور ان کی آل پر رحمتیں نازل فرما جس طرح تو نے ابراہیمؑ اور ان کی آل پر رحمتیں نازل فرمائیں، یقیناً تو تعریف کے لائق اور بڑی بزرگی والا ہے۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/PrayerUponTheProphetAfterTashahhud.mp3",
    duration: "1:10",
    benefits: "The supreme Durood recited in five daily prayers. Brings internal radiance and direct connection to Prophet Muhammad (PBUH)."
  } as unknown as AudioItem,
  {
    id: "darood_taj",
    title: "Durood-e-Taj (درودِ تاج)",
    cardTitle: "Durood-e-Taj",
    arabicTitle: "دُرُودُ التَّاجِ الشَّرِيف",
    category: "darood",
    arabicText: "اللَّهُمَّ صَلِّ عَلَى سَيِّدِنَا وَمَوْلَانَا مُحَمَّدٍ صَاحِبِ التَّاجِ وَالْمِعْرَاجِ وَالْبُرَاقِ وَالْعَلَمِ ۝ دَافِعِ الْبَلَاءِ وَالْوَبَاءِ وَالقَحْطِ وَالْمَرَضِ وَالْأَلَمِ",
    translationText: "O Allah, send blessings upon our Master and Patron Muhammad, the owner of the Crown, the Ascension, the Buraq, and the Standard; the Repeller of calamities, plagues, droughts, sickness, and pain...",
    translationUrdu: "اے اللہ! ہمارے سردار اور ہمارے مولیٰ سیدنا محمد (صلی اللہ علیہ وسلم) پر درود بھیج، جو تاج، معراج، براق اور علم والے ہیں، جو بلا، وبا، قحط، بیماری اور درد کو دور کرنے والے ہیں...",
    audioUrl: "https://archive.org/download/durood-taj_20210428/DuroodTaj.mp3",
    duration: "3:40",
    benefits: "Immense spiritual energy. Recited to heal illnesses, remove dark magic obstacles, and increase outer and inner honor."
  } as unknown as AudioItem,
  {
    id: "darood_tanjina",
    title: "Durood-e-Tanjina (درودِ تنجینا)",
    cardTitle: "Durood-e-Tanjina",
    arabicTitle: "الصَّلَاةُ الْمُنْجِيَة",
    category: "darood",
    arabicText: "اللَّهُمَّ صَلِّ عَلَى سَيِّدِنَا مُحَمَّدٍ صَلَاةً تُنْجِينَا بِهَا مِنْ جَمِيعِ الْأَهْوَالِ وَالْآفَاتِ ۝ وَتَقْضِي لَنَا بِهَا جَمِيعَ الْحَاجَاتِ ۝",
    translationText: "O Allah! Shower blessings on our master Muhammad, such blessings by means of which You may deliver us from all terror and disaster, fulfill all our needs and purify us...",
    translationUrdu: "اے اللہ! ہمارے آقا حضرت محمد (صلی اللہ علیہ وسلم) پر وہ رحمتیں بھیج جن کی برکت سے تو ہمیں تمام خوفوں اور آفتوں سے نجات عطا فرمائے، اور ہماری سب حاجتوں کو پورا کر دے...",
    audioUrl: "https://archive.org/download/darood-tanjeena/darood-tanjeena.mp3",
    duration: "2:10",
    benefits: "An ultimate lifesaver Durood recited during extreme pandemics, natural trials, accidents, or deep economic blockades."
  } as unknown as AudioItem,
  {
    id: "darood_shifa",
    title: "Durood-e-Shifa / Tibb al-Quloob (درودِ شفا)",
    cardTitle: "Durood-e-Shifa",
    arabicTitle: "صَلَاةُ طِبِّ الْقُلُوبِ وَدَوَائِهَا",
    category: "darood",
    arabicText: "اللَّهُمَّ صَلِّ عَلَى سَيِّدِنَا مُحَمَّدٍ طِبِّ الْقُلُوبِ وَدَوَائِهَا وَعَافِيَةِ الْأَبْدَانِ وَشِفَائِهَا وَنُورِ الْأَبْصَارِ وَضِيَائِهَا",
    translationText: "O Allah, send blessings upon our master Muhammad, the medicine of hearts and their cure, the health of bodies and their healing, and the light of eyes and their illumination...",
    translationUrdu: "اے اللہ! درود بھیج ہمارے سردار محمد (صلی اللہ علیہ وسلم) پر جو دلوں کی دوا اور شفا ہیں، اور جسموں کی تندرستی اور عافیت ہیں، اور آنکھوں کا نور اور اجالا ہیں، اور ان کی آل اور اصحاب پر بھی۔",
    audioUrl: "https://archive.org/download/shifa_201908/shifa.mp3",
    duration: "0:50",
    benefits: "Remedy for persistent physical discomfort, cardiovascular pressures, mental distress, and eyesight stabilization."
  } as unknown as AudioItem
];

const JANAZAH_DATA: AudioItem[] = [
  {
    id: "janazah_adult_men_women",
    title: "Namaz-e-Janazah for Adults (بالغ مردوں اور عورتوں کے لیے)",
    cardTitle: "Janazah Adult",
    arabicTitle: "دُعَاءُ صَلَاةِ الْجَنَازَةِ لِلْكِبَارِ",
    category: "janazah",
    arabicText: "اللَّهُمَّ اغْفِرْ لِحَيِّنَا وَمَيِّتِنَا وَشَاهِدِنَا وَغَائِبِنَا وَصَغِيرِنَا وَكَبِيرِنَا وَذَكَرِنَا وَأُنْثَانَا ۝ اللَّهُمَّ مَنْ أَحْيَيْتَهُ مِنَّا فَأَحْيِهِ عَلَى الْإِسْلَامِ وَمَنْ تَوَفَّيْتَهُ مِنَّا فَتَوَفَّهُ عَلَى الْإِيمَانِ",
    translationText: "O Allah, forgive our living and our dead, those present and those absent, our young and our old, our males and our females. O Allah, whomsoever You keep alive among us, keep him alive in Islam, and whomsoever You cause to die, let him die on Faith.",
    translationUrdu: "اے اللہ! بخش دے ہمارے ہر زندہ کو، اور مردہ کو، حاضر کو اور غائب کو، ہمارے چھوٹے کو اور ہمارے بڑے کو، ہمارے مرد کو اور ہماری عورت کو۔ اے اللہ! تو ہم میں سے جس کو زندہ رکھے تو اس کو اسلام پر زندہ رکھ اور جس کو موت دے تو ایمان پر موت دے۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/AtTheFuneralPrayer.mp3",
    duration: "1:05",
    benefits: "Authentic supplication recited during Namaz-e-Janazah for all deceased adult Muslim males and females."
  } as unknown as AudioItem,
  {
    id: "janazah_boy",
    title: "Namaz-e-Janazah for Minor boy (نابالغ لڑکے کے لیے)",
    cardTitle: "Janazah Child Male",
    arabicTitle: "دُعَاءُ جَنَازَةِ الطِّفلِ الذَّكَرِ",
    category: "janazah",
    arabicText: "اللَّهُمَّ اجْعَلْهُ لَنَا فَرَطاً وَاجْعَلْهُ لَنَا أَجْراً وَذُخْراً وَاجْعَلْهُ لَنَا شَافِعاً وَمُشَفَّعاً",
    translationText: "O Allah, make him our forerunner, a source of reward and store, and make him an intercessor and one whose intercession is accepted.",
    translationUrdu: "اے اللہ! اس بچے کو ہمارے لیے آگے پہنچ کر انتظام کرنے والا بنا دے، اور اس کو ہمارے لیے باعثِ اجر و ثواب اور آخرت کا ذخیرہ بنا دے، اور اس کو ہماری سفارش کرنے والا اور وہ جس کی سفارش قبول کی گئی ہو بنا دے۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/AdvancementOfRewardDuringFuneralPrayer.mp3",
    duration: "0:40",
    benefits: "Funeral prayer supplication specifically recited for an un-matured (minor) boy, creating a peaceful path."
  } as unknown as AudioItem,
  {
    id: "janazah_girl",
    title: "Namaz-e-Janazah for Minor girl (نابالغ لڑکی کے لیے)",
    cardTitle: "Janazah Child Female",
    arabicTitle: "دُعَاءُ جَنَازَةِ الصَّبِيَّةِ الْأُنْثَى",
    category: "janazah",
    arabicText: "اللَّهُمَّ اجْعَلْهَا لَنَا فَرَطاً وَاجْعَلْهَا لَنَا أَجْراً وَذُخْراً وَاجْعَلْهَا لَنَا شَافِعَةً وَمُشَفَّعَةً",
    translationText: "O Allah, make her our forerunner, a source of reward and store, and make her an intercessor and one whose intercession is accepted.",
    translationUrdu: "اے اللہ! اس بچی کو ہمارے لیے آگے پہنچ کر انتظام کرنے والی بنا دے، اور اس کو ہمارے لیے باعثِ اجر و ثواب اور آخرت کا ذخیرہ بنا دے، اور اس کو ہماری سفارش کرنے والی اور وہ جس کی سفارش قبول کی گئی ہو بنا دے۔",
    audioUrl: "https://archive.org/download/HisnulMuslim/AdvancementOfRewardDuringFuneralPrayer.mp3",
    duration: "0:42",
    benefits: "Funeral prayer supplication specifically recited for an un-matured (minor) girl, invoking parents' comfort."
  } as unknown as AudioItem
];

// Dynamically compile the entire continuous multi-source Quranic/Dua Audio database
export const ISLAMIC_AUDIO_DATA: AudioItem[] = [
  ...SPIRITUAL_DUAS,
  ...WAZAIF_DATA,
  ...SIX_KALMA_DATA,
  ...CHILDREN_NAMAZ_DATA,
  ...DAROOD_DATA,
  ...JANAZAH_DATA,
  // 114 Surahs Programmatic Generator
  ...SURAH_METADATA.map((s, idx) => {
    const sNum = idx + 1;
    const padded = padThree(sNum);
    
    // Maintain direct backward compatibility for existing bookmarks/deep links
    let customId = `surah_${sNum}`;
    if (sNum === 1) customId = 'fatiha';
    else if (sNum === 112) customId = 'ikhlas';
    else if (sNum === 113) customId = 'falaq';
    else if (sNum === 114) customId = 'nas';

    return {
      id: customId,
      title: `Surah ${s.en} (${s.translation})`,
      arabicTitle: s.ar,
      category: 'quran' as const,
      // Store descriptive indicators so user understands structured division
      arabicText: `سُورَة ${s.ar} — Surah ${sNum} — ${s.type} — ${s.verses} Ayahs`,
      translationText: `Surah ${s.en} ("${s.translation}") contains ${s.verses} Verses. This Surah was revealed in ${s.type}. Key benefit: ${s.benefits}`,
      translationUrdu: `یہ سورہ مبارکہ ${s.urdu} ہے جس میں کل ${s.verses} آیات مبارکہ ہیں۔ اس کے تلاوت کی فضیلت: ${s.benefits}`,
      audioUrl: `https://server8.mp3quran.net/afs/${padded}.mp3`, // Safe, fast public endpoint for Al-Fateh Alzubair
      duration: s.duration,
      benefits: s.benefits
    } as unknown as AudioItem;
  }),
  // 30 JUZ / Paras Programmatic Generator
  ...JUZ_METADATA.map((j, idx) => {
    const jNum = idx + 1;
    const padded = padTwo(jNum);

    return {
      id: `juz_${jNum}`,
      title: `${j.en} [Para ${jNum}]`,
      arabicTitle: j.ar,
      category: 'quran' as const,
      arabicText: `${j.ar} — Chapter ${jNum} — ${j.urdu}`,
      translationText: `${j.en} covers the range: ${j.range}. Benefits and focus: ${j.benefits}`,
      translationUrdu: `پارہ نمبر ${jNum} (${j.urdu}) کے اندر یہ آیات شامل ہیں: ${j.range}۔ تلاوت کی فضیلت: ${j.benefits}`,
      audioUrl: `https://archive.org/download/ParaViseQuranMp3ReciteBySaudAl-Shuraim/${padded}.mp3`, // High-speed, stable public endpoint for Saud Al-Shuraim
      duration: "45:00",
      benefits: j.benefits
    } as unknown as AudioItem;
  })
];

export const INITIAL_TASBIH_DATA: TasbihState[] = [
  {
    id: 'tasbih_fatiha',
    name: 'Astaghfirullah (استغفر اللہ)',
    arabic: 'أَسْتَغْفِرُ اللّٰهَ',
    count: 0,
    goal: 100,
    completedCycles: 0,
  },
  {
    id: 'tasbih_salawat',
    name: 'Durood / Salawat (درود شریف)',
    arabic: 'اَللّٰهُمَّ صَلِّ عَلٰى مُحَمَّدٍ',
    count: 0,
    goal: 33,
    completedCycles: 0,
  },
  {
    id: 'tasbih_subhanallah',
    name: 'SubhanAllah (سبحان اللہ)',
    arabic: 'سُبْحَانَ اللّٰهِ',
    count: 0,
    goal: 33,
    completedCycles: 0,
  },
  {
    id: 'tasbih_alhamdulillah',
    name: 'Alhamdulillah (الحمد للہ)',
    arabic: 'الْحَمْدُ لِلَّهِ',
    count: 0,
    goal: 33,
    completedCycles: 0,
  },
  {
    id: 'tasbih_allahuakbar',
    name: 'Allahu Akbar (اللہ اکبر)',
    arabic: 'اللَّهُ أَكْبَرُ',
    count: 0,
    goal: 34,
    completedCycles: 0,
  }
];
